site_name: CLIMB | Cloud Infrastructure for Microbial Bioinformatics
theme:
  name: material
  logo: assets/logo-square_CLIMB-BIG-DATA.png
  favicon: assets/logo-square_CLIMB-BIG-DATA.png
  features:
    - navigation.sections # Render sections as groups
    - navigation.expand # Expand all sections
    - navigation.path # Breadcrumb navigation
    - navigation.top # Back to top button
    - navigation.indexes # Section index pages
    - navigation.tabs # Top-level tabs
    - navigation.tabs.sticky # Keep tabs visible
    - toc.integrate # Merge with sidebar
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
      primary: indigo
      accent: amber
    - scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
markdown_extensions:
  - attr_list
  - toc:
      permalink: "#"
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - pymdownx.blocks.caption
copyright: |
  Copyright &copy; CLIMB 2026

extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:<climb@quadram.ac.uk>
